### ISSUE TITLE
Generator error : "conflict Wrong content type for Linux64"

### ISSUE THREAD

**Issue by 0gust1** [Dica-Developer/generator-node-webkit#32]
I got a strange error, trying to initialize a nw project (and testing if I can build a linux version under OSX) : 

I told Yeoman to download the 3 versions of NW, and I got this error : "conflict Wrong content type for Linux64" during the attempt to get the L64 version. 

The generator finished in a broken state (missing folder, node dependencies not installed...)

**Comment by drasko** [comment]
Hi all,
I just did npm install -g generator-node-webkit, and I am still seeing the same error:
 conflict     Wrong content type for Linux64
Potentially unhandled rejection [3] Wrong content type for Linux64 (WARNING: non-Error used)

Have this been fixed, and if yes, how to install new version (if not with npm install)?

**Comment by mschaaf** [comment]
We haven't released yet a new version.
