### ISSUE TITLE
issue when running dist application on ubuntu 64

### ISSUE THREAD

**Issue by hems** [Dica-Developer/generator-node-webkit#57]
I just did "grunt dist-linux", then moved the files from my darwin to linux, and then when trying to execute i get this error message

````
./node-webkit 
[2159:1120/165651:ERROR:icu_util.cc(149)] Couldn't mmap /home/beaglert/Desktop/Linux64/icudtl.dat
[2159:1120/165651:FATAL:content_main_runner.cc(716)] Check failed: base::i18n::InitializeICU(). 
Aborted (core dumped)
````

Am i supposed to build the linux dist on a linux computer ?

Shall I try use a different version of node-webkit bin ?

**Comment by mschaaf** [comment]
Thank you @arminhammer for the patch its merged

**Comment by mschaaf** [comment]
Yes it is in the repo but currently not released. So you have to apply the changes yourself or install from the repository.
