### ISSUE TITLE
conflict Wrong content type for Windows for windows 8.1

### ISSUE THREAD

**Issue by yuchuan1** [Dica-Developer/generator-node-webkit#66]
I tried to generate a node-webkit application and got error 'conflict Wrong content type for Windows' running under Windows 8.1
Anyone know what's going on?

     _-----_
    |   |
    |--(o)--|   .--------------------------.
       `---------´  |Welcome to Yeoman,|
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
       __'.___.'__
     ´   `  |° ´ Y `
    
    ? What do you want to call your app? Allowed characters ^[a-zA-Z0-9]+$ (undefine
    ? What do you want to call your app? Allowed characters ^[a-zA-Z0-9]+$ test
    ? A little description for your app? test
    ? Would you mind telling me your username on GitHub? someuser
    ? Do you want to install one of the node-webkit examples? No
       invoke   node-webkit:download
    ? Do you want to download node-webkit? Yes
    ? Please specify which version of node-webkit you want download: (v0.10.5)
     info Check if version "v0.10.5" is available for download.
    ? Please specify which version of node-webkit you want download: v0.10.5
    ? Which platform do you wanna support? Windows
     info Creating folder structure for node-webkit source.
    √ Created: "resources/node-webkit"
    √ Created: "resources/node-webkit/Windows"
    √ Created: "tmp"
     info Downloading node-webkit for Windows
     conflict Wrong content type for Windows
    Potentially unhandled rejection [3] Wrong content type for Windows (WARNING: non
    -Error used)

**Comment by mschaaf** [comment]
It seems that this comes from a redirection we currently not following, but we have a fix for it in the current master. You could try this or wait hopefully only until tomorrow where we plan to release. See issue #61 for more details.
