### ISSUE TITLE
Latest version of NW.JS not detected

### ISSUE THREAD

**Issue by ismaild** [Dica-Developer/generator-node-webkit#67]
Hi,

The generator only detects an old version of NW.JS which is v0.10.5, if you try an enter the latest version i.e 0.11.6 it errors with URL not found.

Though the version exists see: http://dl.nwjs.io/

**Comment by mschaaf** [comment]
It works for me. How did you specify the version?

**Comment by micc83** [comment]
Same problem here:
![screen shot 2015-02-22 at 15 35 07](https://cloud.githubusercontent.com/assets/1750404/6318897/69941f9e-baa8-11e4-8f97-556624b03f49.png)

**Comment by mschaaf** [comment]
> Working ok now but how come v1.0.5 is the default version?

It is because for being up to date with every release we have to update the generator very frequently thats what we have no time for and thats why you can edit it.

**Comment by micc83** [comment]
Hi @mschaaf, I understand. Thank you for the the answer and thank you for generator-node-webkit :smile:
