### ISSUE TITLE
grunt dist-mac or dist mac 32: Unable to build a max osx64 distribution  similar to  #59

### ISSUE THREAD

**Issue by KameshAnandan** [Dica-Developer/generator-node-webkit#69]
I am facing the same issue for both mac32 and mac64 and even for dist-win
1. What sample app you tried? just blank project - no sample 
2. What node-webkit version you are building for? v0.11.6 - 64 bit version
3. What are the exact steps to reproduce? step 1) yo node-webkit ; step 2) grunt dist-mac (or) grunt dist-mac32
4. On what OS you are trying to build the OSX64 dist? OSX 10.8.5

Error seen :

Running "chmod32" task
Warning: ENOENT, no such file or directory 'dist/MacOS32/CM.app/Contents/Frameworks/node-webkit Helper EH.app/Contents/MacOS/node-webkit Helper EH' Use --force to continue.

**Comment by mschaaf** [comment]
If you download the 64bit version you should call the task ```grunt dist-mac```but your output showed you called ```grunt dist-mac32```

**Comment by mschaaf** [comment]
What did you select in the ```yo node-webkit``` step

**Comment by nicesu** [comment]
it also Running "chmod64" task
Warning: ENOENT, no such file or directory 'dist/MacOS32/CM.app/Contents/Frameworks/node-webkit Helper EH.app/Contents/MacOS/node-webkit Helper EH' Use --force to continue.

**Comment by KameshAnandan** [comment]
The below is the copy from my terminal : 

? What do you want to call your app? Allowed characters ^[a-zA-Z0-9]+$ Test
? A little description for your app? 
? Would you mind telling me your username on GitHub? someuser
? Do you want to install one of the node-webkit examples? No
   invoke   node-webkit:download
? Do you want to download node-webkit? No
     info     Creating folder structure for node-webkit source.
✔ Created: "resources/node-webkit"
✔ Created: "tmp"
   create .editorconfig
   create .jshintrc
   create .gitignore
   create bower.json
   create resources/mac/dmgStyler.applescript
   create resources/mac/package.sh
   create resources/mac/background.png
   create package.json
   create Gruntfile.js
   create resources/mac/Info.plist.tmp
   create resources/mac/Info.plist
   create app/css/main.css
   create app/js/index.js
   create app/package.json
   create app/views/index.html

**Comment by mschaaf** [comment]
> Do you want to download node-webkit? No

Could you please try with downloading the node-webkit and select there the osx 64 version. Maybe you did not download before a version or it is removed.

**Comment by mschaaf** [comment]
@nicesu Please add the complete output from ```yo node-webkit``` until ```grunt dist-?```? With all the answers included. Thank you.

**Comment by KameshAnandan** [comment]
The below is what I see when I say yes to download node-webkit  when I selected to download node-webkit.

? What do you want to call your app? Allowed characters ^[a-zA-Z0-9]+$ Test
? A little description for your app? 
? Would you mind telling me your username on GitHub? someuser
? Do you want to install one of the node-webkit examples? No
   invoke   node-webkit:download
? Do you want to download node-webkit? Yes
? Please specify which version of node-webkit you want download: (v0.10.5) v0.11.6
     info     Check if version "v0.11.6" is available for download.
? Please specify which version of node-webkit you want download: v0.11.6
? Which platform do you wanna support? MacOS 64, Windows
     info     Creating folder structure for node-webkit source.
✔ Created: "resources/node-webkit"
✔ Created: "resources/node-webkit/MacOS64"
✔ Created: "resources/node-webkit/Windows"
✔ Created: "tmp"
     info     Downloading node-webkit for MacOS64
     info     Downloading node-webkit for Windows
 conflict     Wrong content type for MacOS64
Potentially unhandled rejection [3] Wrong content type for MacOS64 (WARNING: non-Error used)
 conflict     Wrong content type for Windows

**Comment by KameshAnandan** [comment]
I downloaded the node-webkit and manually copied it to the resources folder, everything seems to be fine  after that.

**Comment by mschaaf** [comment]
> Potentially unhandled rejection [3] Wrong content type for MacOS64 (WARNING: non-Error used)

There it is it is not downloaded. I guess this is fixed in current master we will provide an updated generator in the days. It should be fixed with #61
