### ISSUE TITLE
Support for v0.12.0?

### ISSUE THREAD

**Issue by christomitov** [Dica-Developer/generator-node-webkit#70]
Looks like naming changed which messes up the URLs now. The release is under "nwjs" not "node-webkit" unfortunately this breaks the gruntfile also. I'm going through it right now to try and patch it hopefully if I get time I can PR this?? If not a fix would be awesome.

**Comment by mschaaf** [comment]
Thanks for reporting. We need to handle both variants. I will have a look at this.

**Comment by mschaaf** [comment]
Before we release it is necessary to QA the changes against the windows, linux builds.
