### ISSUE TITLE
Module not found issues on Linux and Windows builds

### ISSUE THREAD

**Issue by vinaygopinath** [Dica-Developer/generator-node-webkit#73]
Third-party node modules cause "module not found" errors when require() is called.

@commadelimited's solution (#22) for Mac builds, though functional, copies all the directories in node_modules into the final package. This is quite expensive in terms of bloat because there is no need for dev dependencies to be present in the dist package.

A workaround is to add a block for each module under `appLinux` (My app uses mysql)

```javascript
appLinux: {
                files: [{
                    expand: true,
                    cwd: '<%= config.app %>',
                    dest: '<%= config.distLinux64 %>/app.nw',
                    src: '**'
        }, {
                    expand: true,
                    cwd: 'node_modules',
                    dest: '<%= config.distLinux64 %>/app.nw/node_modules/',
                    src: 'mysql/**'
                    }]
            }
```

There has to be a better way of doing this, though. I tried adding a new config property like so
```javascript
dependencies: grunt.file.readJSON('package.json').dependencies
```
and mucked around with globbing patterns, but couldn't get it to work. I also tried looping through the `keys` of the `dependencies` object and running `grunt.file.copy` based on the answers to [this SO question](http://stackoverflow.com/questions/25129330/grunt-can-you-call-grunt-contrib-copy-from-within-a-custom-registered-task-and)

Someone better versed with grunt config should be able to automate the process of copying dependencies (and not devDependencies) into the dist package of all three platforms.

**Comment by mschaaf** [comment]
Where is your package.json located within your project folder?

**Comment by vinaygopinath** [comment]
The package.json is in the root of the project folder.
I'm running into this issue even when I make a build after doing a clean run of the generator, installing mysql as an npm dependency and calling require() in a JS file. The Windows and Linux builds work as long as they're in the dist folder, but moving them to a different folder causes the "module not found" errors, so I'm guessing there's some node_modules relative path issue underneath.

**Comment by mschaaf** [comment]
Ok the main package.json is not the place for your apps deps. This package.json is for the generator itself. There should be an app folder in the root folder and in within this there needs to be the node_modules folder located. It should contain all your production dependencies. You can call npm install <production module> directly in this folder as a workaround and put a shell script in this folder which calls the necessary installation steps.

Maybe a better solution is to use inside of the generator a mechanism to specify all the production dependencies and then use npm install programmatically from within the grunt file.
