### ISSUE TITLE
grunt dmg doesn't work in v1.0.4

### ISSUE THREAD

**Issue by sambaker** [Dica-Developer/generator-node-webkit#74]
Maybe this is premature since v1.0.4 isn't in the releases list yet but the grunt dmg task successfully creates the dmg, however when you open the image, the app inside won't run.

You can run the executable *inside* the Mac application package using the command line to get to the nwjs executable but the app that you drag to your Applications folder is broken.

**Comment by sambaker** [comment]
I picked all default options, including v0.12.0 of node-webkit. I also changed config.distMac32 in Gruntfile.js to be 'macOS' instead of 'MacOS32' to work around https://github.com/Dica-Developer/generator-node-webkit/issues/75

**Comment by mschaaf** [comment]
Is pull request #76 fixing this too?

**Comment by sambaker** [comment]
No, I don't know what the cause of this one is.



On May 12, 2015, at 5:07 AM, Schaaf, Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


Is pull request #76<https://github.com/Dica-Developer/generator-node-webkit/pull/76> fixing this too?

-

**Comment by mschaaf** [comment]
to you have error message? did packaging an example app work?

**Comment by sambaker** [comment]
The example apps have the same problem. A repro is:
`yo node-webkit` - select all default options on a new project, same results with or without installing an example
`grunt dist-mac`
`grunt dmg`
`open dist/macOS/generatorNodeWebkitTest.dmg`
When the dmg opens, the icon for the app has a circle over it, then if you run it you it fails with the message `You can’t open the application “generatorNodeWebkitTest” because it may be damaged or incomplete.`

**Comment by sambaker** [comment]
Update: I tried the same repro steps except I picked v0.10.5 of node-webkit instead of v0.12.0 and that worked fine. So it's a problem only with newer versions of node-webkit, probably related to the name change to nwjs.

**Comment by mschaaf** [comment]
Thanks for testing I will have a look at it.

**Comment by mschaaf** [comment]
In the plist file is still the wrong executable referenced. I will push a fix.

**Comment by sambaker** [comment]
So it is - thanks for fixing.

**Comment by mschaaf** [comment]
fixed with commit 2ddb91aa808686f4eb9c923fddcbf2f1f205fa1d
