### ISSUE TITLE
grunt dmg script has wrong path

### ISSUE THREAD

**Issue by sambaker** [Dica-Developer/generator-node-webkit#75]
The resources/mac/package.sh script attempts to create the disk image from the contents of dist/macOS. However the grunt-mac and grunt-mac32 scripts create the builds in MacOS32 and MacOS64 instead. There are a couple of ways to fix this, if you have a preference I'm happy to make the change and create a pull request.

**Comment by mschaaf** [comment]
Providing an pull request is very welcome. I would prefer to create the same folder dist/macOS for both versions and don't separate between the bit count.

**Comment by sambaker** [comment]
I created a pull request - sharing the dist/macOS folder makes it a simple fix. The tests in the build are failing but that's unrelated to my change. Thanks for the generator, it's been very useful.

**Comment by mschaaf** [comment]
Thanks for your help. I close it now because the pull request is accepted and merged.
