### ISSUE TITLE
File Manager example is broken

### ISSUE THREAD

**Issue by kevinsimper** [Dica-Developer/generator-node-webkit#79]
Just tried yo node-webkit and selected the File Manager and the example is too outdated.

Running on mac, and then running `grunt dist-mac` does not work, because of JShint errors.

**Comment by mschaaf** [comment]
You have to run it with the option --force. is this the only problem you run in with this example?

**Comment by kevinsimper** [comment]
Yes, it works! Thanks :)

**Comment by mschaaf** [comment]
Close as clarified
