### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by helloncanella** [Dica-Developer/generator-node-webkit#83]
For some reason when I type `grunt`, when within the folder, I receive the message:

```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
helloncanella@yoga:~/code/giz$ rm -r giz
rm: cannot remove ‘giz’: No such file or directory
```

even with ``gruntfile`` created.

**Comment by helloncanella** [comment]
After a *npm install*, I've got the following error

*
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
*

**Comment by mschaaf** [comment]
Thank you for trying generator-node-webkit.
Do be able to help you we need the exact steps to reproduce.

**Comment by helloncanella** [comment]
The steps

1. After the installation of generator, when within a folder (on the terminal), I typed `yo node-webkit`
2.  On the information `npm install & bower install` the process stops, so I need to do it manually 
3.  After that, when I type `grunt` I receive the following message

```
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-09-25 01:29:52 UTC)
loading tasks  723ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 725ms


```

**Comment by mschaaf** [comment]
What did you answer on the question from ```yo node-webkit```?
Did you install a sample application?

**Comment by helloncanella** [comment]
I've tried the both options: to install and not to install. Following the suggestion of the question, I've installed a sample application, but the results I get are the same.

**Comment by mschaaf** [comment]
1. call npm install
2. call bower install
3. call grunt dist-<os dependent> -f // -f is only necessary for the example applications

Then the dist will be created. Have a look at our wiki (https://github.com/Dica-Developer/generator-node-webkit/wiki) .  There is described how to start developing with generator-node-webkit https://github.com/Dica-Developer/generator-node-webkit/wiki/Getting-Started
